sudo: false

python:
- 2.7
- 3.5

env:
- CONDA_DEPS="dipy nose" PIP_DEPS="xvfbwrapper" TEST_WITH_XVFB=true MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- command -v conda >/dev/null || { wget $MINICONDA_URL -O miniconda.sh; bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda config --add channels conda-forge
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS

script:
  # No figure Windows for Matplotlib:
  - 'echo "backend : agg" > matplotlibrc'
  - python run_test.py
