language: python
sudo: false

env:
  global:
    - CONDA_DEPS="dipy nose"

matrix:
  include:
    - os: osx
      env:
         - PYTHON_VERSION=2.7
    - os: osx
      env:
         - PYTHON_VERSION=3.5
    - os: linux
      env:
         - PYTHON_VERSION=2.7
    - os: linux
      env:
         - PYTHON_VERSION=3.5

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda install python=$PYTHON_VERSION $CONDA_DEPS

script:
- python run_test.py
